version: 2
jobs:
  build:
    docker:
      - image: docker:17.11.0-ce
    working_directory: ~/workspace
    environment:
      OWNER: emojigen
      IMAGE_NAME: docker-node-py2
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: docker build -t $OWNER/$IMAGE_NAME:latest .
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push image to registory
          shell: /bin/bash -eu -o pipefail
          command: |
            NODE_VERSION=fgrep 'node:' Dockerfile | sed -E 's/^.*node\:([0-9\.]+).*$/\1/'
            echo $NODE_VERSION

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $OWNER/$IMAGE_NAME
            fi
